### ISSUE TITLE
Fork and release as GBike and GHike

### ISSUE THREAD

**Issue by mirko77** [gcormier9/GRun#1]
Hi there, I really like the data field, nice job!.

I was thinking about forking this repo and release a couple of clones with some tweaks for mountain biking and hiking, so GBike and GHike, obviously acknowledging your hard work.

Are you ok with me doing that?

Cheers

**Comment by gcormier9** [comment]
Indeed I am ok! That's why the code is on GitHub!

**Comment by gcormier9** [comment]
BTW, you can use any names for your new datafields. If you don't like
GBike/GHike, etc., feel free to use whatever you like!

**Comment by mirko77** [comment]
Brilliant, thanks!

**Comment by yorkshirelad99** [comment]
Did this ever become a different data field for hiking / cycling? I'd be very interested in using it. I can't see one on the connect iq

**Comment by yorkshirelad99** [comment]
OK, thanks
