### ISSUE TITLE
Average cadence

### ISSUE THREAD

**Issue by bjebb** [gcormier9/GRun#12]
Using Forerunner 245 Average Cadence seem to need a factor 2 adjustment, showing 90 instead of 180.

**Comment by gcormier9** [comment]
I believe this is a firmware issue. Garmin will have to fix it, if not already done...

**Comment by bjebb** [comment]
Could be, but the standard average cadence (medelkadens on my swedish setting) added on a two field custom view works though.

![BEB2ACF2-BD91-4468-A50B-661564803ECD](https://user-images.githubusercontent.com/55667792/153039767-fd46d4f5-6c4a-4e64-a305-989d19c7f671.jpeg)

![8C560B68-344B-4095-B6AD-DA76D996A9BB](https://user-images.githubusercontent.com/55667792/153039744-9b03591c-1c19-486c-b284-a32e6f510387.jpeg)

**Comment by gcormier9** [comment]
From what I have seen on the Garmin forum, this issue only affect CIQ (custom application/datafield). However, I haven't personnally used Average Pace myself and have read couple of places that we have to multiply the value returned by Garmin by 2 to workaround the problem. I'll try it on my watch later on and come back to you.

**Comment by bjebb** [comment]
Thanks!

**Comment by gcormier9** [comment]
I have opened a defect with Garmin. Waiting for their reply...
https://forums.garmin.com/developer/connect-iq/i/bug-reports/bug-info-averagecadence-is-half-of-info-currentcadence

Thanks,
GCorm

**Comment by gcormier9** [comment]
Fix in V1.34

**Comment by bjebb** [comment]
Many thanks!

Den fre 8 apr. 2022 kl 03:16 skrev gcormier9 ***@***.***>:

**Comment by gcormier9** [comment]
Thanks for the donation! You really made my day!
