### ISSUE TITLE
Smoothed pace

### ISSUE THREAD

**Issue by Mushin** [gcormier9/GRun#9]
Apologies if this is described somewhere in the documentation - I couldn't find it.

Please could you clarify if the pace displayed is the current (instantaneous) pace?

If so, is it possible to add a smoothed average (e.g. 5 second average)?

Thanks

**Comment by gcormier9** [comment]
Hi,

Smooth average is already available, but only on high-memory devices. The
metric is called "Average Pace (Last X sec)".

Regards
GCorm

**Comment by Mushin** [comment]
Thanks - found it. I was looking under P (for pace).

I was also wondering - is it possible to show headers for row 4? Thanks for the great app.
